$(function(){if($('.secondList')[0]){navInteract();};if($('.rollBanner')[0]){playRoll();}
if($('.occupation').length){switchResume();}
if($('.aboutMain .sideBar').length){scrollSideBar();}});function playRoll(){var arrImg=$('.rollBanner .wrap img');var arrBtn=$('.rollBanner .btnGroup span');$.tod.playRoll({wrapped:arrImg,btn:arrBtn,activeBtn:'active'});}
function scrollSideBar(){var objEle=$('.sideBar');var timePlay=400;$(window).scroll(function(){var top=$(window).scrollTop();if(top>400){var posY=top-400;objEle.stop().animate({'top':posY},timePlay)}else{objEle.stop().animate({'top':0},timePlay)}})}
function switchResume(){var arrBtn=$('.occupation .slideBtn');var arrFold=$('.occupation .fold');var arrOccuSpec=$('.occuSpec');var heightBox=$('.occuSpec').height()+20;var topBox=$('.occuSpec').css('top');var playTime=400;var unfoldBox={};var unfoldTex={};arrBtn.each(function(i){arrBtn[i].index=i;arrFold[i].index=i;arrOccuSpec[i].index=i;$(this).click(function(){if(unfoldBox.length){if($(this).html()=='关闭'){unfoldBox.addClass('fold');unfoldBox.stop().animate({height:50},playTime);unfoldTex.html('查看');$(arrOccuSpec[i]).stop().animate({top:-50},playTime);}else{unfoldBox.addClass('fold');unfoldBox.stop().animate({height:50},playTime);unfoldTex.html('查看');unfoldBox.find('.occuSpec').stop().animate({top:-50},playTime);$(arrBtn[i]).html('关闭');$(arrFold[i]).stop().animate({height:heightBox},playTime,function(){$(this).removeClass('fold');unfoldBox=$(this);unfoldTex=$(arrBtn[i]);});$(arrOccuSpec[i]).stop().animate({top:0},playTime);}}else{$(arrBtn[i]).html('关闭');$(arrFold[i]).stop().animate({height:heightBox},playTime,function(){$(this).removeClass('fold');unfoldBox=$(this);unfoldTex=$(arrBtn[i]);})
$(arrOccuSpec[i]).stop().animate({top:0},playTime);}})})}
function navInteract(){var navList=$('.nav li:gt(0)');var secList=$('.secondList ul');navList.each(function(i){navList[i].index=i;secList[i].index=i;$(this).click(function(){$(secList[this.index]).stop().slideDown('fast');})
$(this).mouseout(function(){$(secList[this.index]).stop().slideUp('fast');})});secList.each(function(i){$(this).hover(function(){$(secList[this.index]).stop().slideDown('fast');},function(){$(secList[this.index]).stop().slideUp('fast');})})}
jQuery.tod={popMask:function(child,options){if(!child){alert('弹出层获取失败！');return false;}
var defaults=options;var mask=$('.pop-mask');if(mask[0]){var display=mask.css('display');if(display=='block'){return false;}
cssStyle();popup();}else{mask=document.createElement('div');var body=$('body');mask=$(mask);mask.attr('class','pop-mask');cssStyle();popup();body.append(mask[0]);}
$(window).resize(function(){cssStyle();})
$(window).scroll(function(){cssStyle();});$(window).keydown(function(e){switch(e.keyCode){case 27:closePop();break;}});if(defaults.btnClose){var btnClose=defaults.btnClose;btnClose.click(function(){closePop();});}
function popup(){child.css({'z-index':10});mask.fadeIn(100,function(){handleDefaults();child.slideDown();});}
function closePop(){child.slideUp(function(){mask.fadeOut('fast');});}
function handleDefaults(){if(!defaults){return false;};if(defaults.time){var time=defaults.time;var eleVar=defaults.TimeValue;eleVar.html(time);var objTimer=setInterval(function(){time-=1;eleVar.html(time);if(time==0){clearInterval(objTimer);closePop();}},1000)}
if(defaults.title){var obj=defaults.title;var text=defaults.titText;obj.html(text);}
if(defaults.user){defaults.user.obj.css({'background-position':defaults.user.css})}}
function cssStyle(){var width=$(window).width();var height=$(document).height();var scrollTop=$(window).scrollTop();var childWidth=child.width();mask.css({'position':'absolute','top':0,'left':0,'z-index':9,'width':width,'height':height,'background':'#333','opacity':0.9});child.css({'left':(width-childWidth)/2+'px','top':50+scrollTop})}},playRoll:function(options){var wrap=options.wrapped;var btn=options.btn;var activeClass=options.activeBtn;var index=0;var timer=null;var timeInterval=3000;reset();btn.each(function(i){$(this).click(function(){if(index==i){return false;}
index=i;wrap.fadeOut();$(wrap[i]).fadeIn();})});btn.hover(function(){btn.removeClass(activeClass);clearInterval(timer);},function(){play();});play();function play(){timer=setInterval(function(){index++;wrap.fadeOut();if(index==wrap.length){index=0;}
$(wrap[index]).fadeIn();btn.removeClass(activeClass);$(btn[index]).addClass(activeClass);},timeInterval)};function reset(){wrap.hide();$(wrap[0]).show();}}}